In [4]:
import numpy as np
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# One hot encoding
    # class 0 -> [1,0,0]
    # class 1 -> [0,1,0]
    # class 2 -> [0,0,1]

from tensorflow.keras.utils import to_categorical

y = to_categorical(y)
print(y.shape)

(150, 3)


In [12]:
# Train test split and Scaling
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler # for normalization between 0 and 1

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
scaler = MinMaxScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
# Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax')) # At the end to show probablity of each class
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary() # To see the architecture of the model

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(X_train,y_train,epochs=150,verbose=2) 
# verbose=0 to ignore the output
# verbose=1 to see the progress
# verbose=2 to see the progress and the output

Epoch 1/150
4/4 - 1s - loss: 1.1655 - accuracy: 0.6400 - 1s/epoch - 293ms/step
Epoch 2/150
4/4 - 0s - loss: 1.1558 - accuracy: 0.6500 - 8ms/epoch - 2ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1464 - accuracy: 0.6500 - 23ms/epoch - 6ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1378 - accuracy: 0.6500 - 9ms/epoch - 2ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1289 - accuracy: 0.6500 - 31ms/epoch - 8ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1201 - accuracy: 0.6500 - 19ms/epoch - 5ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1115 - accuracy: 0.6500 - 6ms/epoch - 2ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1014 - accuracy: 0.6500 - 7ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0902 - accuracy: 0.6500 - 9ms/epoch - 2ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0785 - accuracy: 0.6500 - 14ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0667 - accuracy: 0.6500 - 28ms/epoch - 7ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0556 - accuracy: 0.6500 - 96ms/epoch - 24ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0456 - accuracy: 0.65

In [19]:
# Converting One hot encoding to integer(class)

print(np.argmax(model.predict(X_test), axis=-1)) # gives the class predicted but not one hot encoded
y_pred = np.argmax(model.predict(X_test), axis=-1)
y_test.argmax(axis=1) # gives the class predicted

[1 0 2 1 2 0 1 2 2 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2]


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [20]:
# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(confusion_matrix(y_test.argmax(axis=1), y_pred))
print(classification_report(y_test.argmax(axis=1), y_pred))
print(accuracy_score(y_test.argmax(axis=1), y_pred))

[[19  0  0]
 [ 0 13  2]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

0.96


In [21]:
# Saving the model
model.save('iris_model.h5')

# Loading the model
from tensorflow.keras.models import load_model
new_model = load_model('iris_model.h5')
new_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________
